package p15188966.wateranalysisapp;

import org.json.JSONArray;
import org.json.JSONException;
import org.json.JSONObject;

/**
 * An object to represent a singular Reading consisting of a Date, RGB values,
 * User Nitrate Value, and App Calculated Nitrate Value.
 */
class Reading {

    /**
     * Date, generated by app at time of reading
     */
    private String date;
    /**
     * RGB values from the Image Pixel tapped by the user
     */
    private int red, green, blue;
    /**
     * A nitrate value chosen by the User, engineered to be zero by default
     */
    private int userNitrate;
    /**
     * Nitrate ppm value calculated in the ImageTouchActivity, limited to two decimal places
     */
    private double appNitrate;

    /**
     * Defaut constructor, allows the ImageTouchActivity to assign each variable independently
     */
    Reading() {
        this.date = "";
        this.red = 999;
        this.green = 999;
        this.blue = 999;
        this.userNitrate = 999;
        this.appNitrate = 999;
    }

    /**
     * Full constructor used by Past Readings activity to assign all vaiables at once
     *
     * @param date        Date generated at time of reading
     * @param red         Red value of pixel tapped by user
     * @param green       Green value of pixel tapped by user
     * @param blue        Blue value of pixel tapped by user
     * @param userNitrate Selected by user
     * @param appNitrate  Calculated by app
     */
    Reading(String date, int red, int green, int blue, int userNitrate, double appNitrate) {
        this.date = date;
        this.red = red;
        this.green = green;
        this.blue = blue;
        this.userNitrate = userNitrate;
        this.appNitrate = appNitrate;
    }

    /**
     * Returns date string
     *
     * @return date
     */
    public String getDate() {
        return date;
    }

    /**
     * set date variable
     *
     * @param date date string
     */
    public void setDate(String date) {
        this.date = date;
    }

    /**
     * Returns Red int
     *
     * @return Red int
     */
    public int getRed() {
        return red;
    }

    /**
     * Sets Red value
     *
     * @param red red int
     */
    public void setRed(int red) {
        this.red = red;
    }

    /**
     * Returns Green int
     *
     * @return Green int
     */
    public int getGreen() {
        return green;
    }

    /**
     * Sets Green valeue
     *
     * @param green Green int
     */
    public void setGreen(int green) {
        this.green = green;
    }

    /**
     * Returns Blue int
     *
     * @return Blue int
     */
    public int getBlue() {
        return blue;
    }

    /**
     * Sets Blue int
     *
     * @param blue Blue int
     */
    public void setBlue(int blue) {
        this.blue = blue;
    }

    /**
     * Returns user nitrate int
     *
     * @return user nitrate int
     */
    public int getUserNitrate() {
        return userNitrate;
    }

    /**
     * Set User Nitrate int
     *
     * @param userNitrate User Nitrate int
     */
    public void setUserNitrate(int userNitrate) {
        this.userNitrate = userNitrate;
    }

    /**
     * Returns app nitrate double
     *
     * @return app nitrate double
     */
    public double getAppNitrate() {
        return appNitrate;
    }

    /**
     * Sets App Nitrate double
     *
     * @param appNitrate App Nitrate double
     */
    public void setAppNitrate(double appNitrate) {
        this.appNitrate = appNitrate;
    }

    /**
     * Converts object to JSON Object and returns as string ready to write to file
     *
     * @return JSON obejct as String
     */
    public String toJSONString() {
        //Creates object
        JSONObject readings = new JSONObject();
        //Adds all data to object
        try {
            readings.put("Date", date);
            readings.put("Red", red);
            readings.put("Green", green);
            readings.put("Blue", blue);
            readings.put("App Nitate", appNitrate);
            readings.put("User Nitrate", userNitrate);
        } catch (JSONException e) {
            e.printStackTrace();
        }
        //Adds reading to array
        JSONArray jsonArray = new JSONArray();
        jsonArray.put(readings);
        //Adds array to final object
        JSONObject finalObj = new JSONObject();
        try {
            finalObj.put("Readings", jsonArray);
        } catch (JSONException e) {
            e.printStackTrace();
        }
        //returns object as a string
        return finalObj.toString();
    }

    /**
     * Converts object to beautifully formatted string ready to face user
     *
     * @return Beauty format String
     */
    public String toFormattedJSONString() {
        return "Date: " + date + "\n" +
                "Red: " + red + "\n" +
                "Green: " + green + "\n" +
                "Blue: " + blue + "\n" +
                "App Nitrate: " + appNitrate + "\n" +
                "User Nitrate: " + userNitrate;
    }
}